when:
  - event: push
    branch: main

steps:
  - name: build-and-push
    image: woodpeckerci/plugin-docker-buildx
    settings:
      platforms: linux/amd64,linux/arm64
      registry: git.prijindal.click
      username: prijindal
      password:
        from_secret: PACKAGE_TOKEN
      auto_tag: true
      repo: git.prijindal.click/${CI_REPO}
      cache-from:
        - type=registry\\,ref=git.prijindal.click/${CI_REPO}:buildcache
      cache-to: type=registry,ref=git.prijindal.click/${CI_REPO}:buildcache,mode=max